### PR TITLE
fix: remove FirstIdx attribute of LXRHash

### LINKED ISSUE #57: Race condition detected because of FirstIdx assignment
When using LXRHash concurrently the Golang race condition detector will report something like this:

```bash
WARNING: DATA RACE
Write at 0x0000016da3c0 by goroutine 79:
  github.com/pegnet/LXRHash.(*LXRHash).Hash()
      /home/paul/go/pkg/mod/github.com/pegnet/!l!x!r!hash@v0.0.0-20190806215027-2c3ac3baf00d/lxrhash.go:101 +0x48b

Previous write at 0x0000016da3c0 by goroutine 78:
  github.com/pegnet/LXRHash.(*LXRHash).Hash()
      /home/paul/go/pkg/mod/github.com/pegnet/!l!x!r!hash@v0.0.0-20190806215027-2c3ac3baf00d/lxrhash.go:101 +0x48b
```
Which points to this assignment: https://github.com/pegnet/LXRHash/blob/master/lxrhash.go#L101
While I understand it doesn't have any impact on the LXR hash produced, it's annoying to have this warning shows up when testing my own software that uses LXR hash. Could this be somehow fixed so that this false-positive doesn't show up when testing race conditions? Thank you.

### PR DESCRIPTION
**Pull request by PaulBernier**
fix https://github.com/pegnet/LXRHash/issues/57

### CODE REVIEW

File: lxrhash.go [hunk 1]
```diff
@@ -93,13 +92,10 @@ func (lx *LXRHash) Hash(src []byte) []byte {
 
 	idx = 0
 	// Actual work to compute the hash
-	for i, v2 := range src {
+	for _, v2 := range src {
 		if idx >= lx.HashSize { // Use an if to avoid modulo math
 			idx = 0
 		}
-		if i == 0 {
-			lx.FirstIdx = (as>>5 ^ uint64(v2)) & mk
```
Comment (PaulSnow) [inline lxrhash.go:101]: Adam Levy suggested removing the pointer receiver from the Hash function.  It was needed so that we _could set lx.FirstIdx_.  Since we are not, we can remove it.

Does add copying that we are now avoiding, but I doubt the difference is measurable.

Comment (PaulBernier) [reply lxrhash.go:101]: Sure, removed.

**Review by PaulSnow — APPROVED** [review]
Adam Levy suggested we remove the pointer receiver here (was a pointer to communicate out the value of FirstIdx)

**Review by PaulSnow — APPROVED** [review]
